import type { NextPage } from "next";

import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import styles from "../../styles/Home.module.css";
import { getGenerationList } from "../../services/pokeService";
import { generationRanges } from "../../helpers/generationRanges";
import { Nav } from "../../components/Nav";
import { Table } from "../../components/Table";
import { generationName } from "../../helpers/generationName";

import genStyles from "./index.module.css";

type TableData = [
  {
    name: string;
    url: string;
  },
];

const GenerationList: NextPage = () => {
  const [generationList, setGenerationList] = useState<TableData | null>(null);
  const [genName, setGenName] = useState<string | null>(null);

  const router = useRouter();
  const { gen } = router.query;

  useEffect(() => {
    const { start, end } = generationRanges(gen as string);

    if (gen) {
      const genName = generationName(gen as string);

      getGenerationList(start, end).then((data) => {
        setGenerationList(data.data.results);

        setGenName(genName);
      });
    }
  }, [gen]);

  const TITLES = ["Name", "Actions"];

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokenext!</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header>
        <Nav />
      </header>
      <main className={styles.main}>
        {genName && <h1 className={genStyles["generation-name"]}> {genName} </h1>}
        {generationList && <Table data={generationList} titles={TITLES} />}
      </main>
    </div>
  );
};

export default GenerationList;
