import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { FlexContainer } from "../../components/FlexContainer";
import { TypeIcon } from "../../components/TypeIcon";
import { TYPES } from "../../constants/constants";
import HeaderLayout from "../../layouts/HeaderLayout";
import { MainLayout } from "../../layouts/MainLayout";

const Types: NextPage = () => {
  return (
    <div className="app-container">
      <Head>
        <title>Pokenext!</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <HeaderLayout />
      <MainLayout>
        <FlexContainer>
          {TYPES.map((type, index) => (
            <div key={index} className="flex flex-col justify-center content-center">
              <Link href={`/types/${type}`} passHref={true}>
                <button type="button">
                  <TypeIcon height={100} type={type} width={100} />
                  <p className="text-center capitalize font-secondary pt-1 font-bold text-medium text-blue">
                    {type}
                  </p>
                </button>
              </Link>
            </div>
          ))}
        </FlexContainer>
      </MainLayout>
    </div>
  );
};

export default Types;
