import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Nav } from "../../components/Nav";
import { TYPES } from "../../constants/constants";
import { MainLayout } from "../../layouts/MainLayout";

const Types: NextPage = () => {
  return (
    <div className="app-container">
      <Head>
        <title>Pokenext!</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header>
        <Nav />
      </header>
      <MainLayout>
        {TYPES.map((type, index) => (
          <Link key={index} href={`/types/${type}`} passHref={true}>
            <button type="button">{type}</button>
          </Link>
        ))}
      </MainLayout>
    </div>
  );
};

export default Types;
