import type { NextPage } from "next";

import Head from "next/head";

import { Nav } from "../components/Nav";
import { HomeContainer } from "../containers/Home";
import { MainLayout } from "../layouts/MainLayout";

const Home: NextPage = () => {
  return (
    <div className="app-container">
      <Head>
        <title>Pokenext!</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header>
        <Nav />
      </header>
      <MainLayout>
        <HomeContainer />
      </MainLayout>
    </div>
  );
};

export default Home;
