import type { NextPage } from "next";

import { useEffect, useState } from "react";
import Head from "next/head";

import { getPokemonByNumber } from "../../services/pokeService";
import { fetchInfoData, InfoData } from "../../services/fetchInfoData";
import { InfoCard } from "../../components/InfoCard";
import { MainLayout } from "../../layouts/MainLayout";
import HeaderLayout from "../../layouts/HeaderLayout";
import useNavigation from "../../hooks/useNavigation";

const PokemonInfo: NextPage = () => {
  const [pokemon, setPokemon] = useState<InfoData | null>(null);
  const { handleNext, handlePrev, currentId } = useNavigation({ min: 1, max: 1126 });

  useEffect(() => {
    if (currentId) {
      getPokemonByNumber(currentId as string).then((data) => {
        const fetchedData = fetchInfoData(data.data);

        setPokemon(fetchedData);
      });
    }

    return () => {};
  }, [currentId]);

  return (
    <div className={"app-container"}>
      <Head>
        <title>Pokenext!</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <HeaderLayout />
      {pokemon && (
        <MainLayout>
          <InfoCard
            abilities={pokemon.abilities}
            base_experience={pokemon.base_experience}
            front_default={pokemon.front_default}
            handleNext={handleNext}
            handlePrev={handlePrev}
            height={pokemon.height}
            id={pokemon.id}
            name={pokemon.name}
            stats={pokemon.stats}
            types={pokemon.types}
            weight={pokemon.weight}
          />
        </MainLayout>
      )}
    </div>
  );
};

export default PokemonInfo;
