import type { NextPage } from "next";

import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

import { getPokemonByNumber } from "../../services/pokeService";
import { fetchInfoData, InfoData } from "../../services/fetchInfoData";
import { Nav } from "../../components/Nav";
import { InfoCard } from "../../components/InfoCard";
import { MainLayout } from "../../layouts/MainLayout";

const PokemonInfo: NextPage = () => {
  const [pokemon, setPokemon] = useState<InfoData | null>(null);

  const router = useRouter();
  const { id } = router.query;

  const handleNext = () => {
    if (Number(id) < 898) {
      router.push(`/pokemon/${Number(id) + 1}`);
    }
  };

  const handlePrev = () => {
    if (Number(id) > 1) {
      router.push(`/pokemon/${Number(id) - 1}`);
    }
  };

  useEffect(() => {
    if (id) {
      getPokemonByNumber(id as string).then((data) => {
        const fetchedData = fetchInfoData(data.data);

        setPokemon(fetchedData);
      });
    }

    return () => {};
  }, [id]);

  return (
    <div className={"app-container"}>
      <Head>
        <title>Pokenext!</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header>
        <Nav />
      </header>
      {pokemon && (
        <MainLayout>
          <InfoCard
            abilities={pokemon.abilities}
            base_experience={pokemon.base_experience}
            front_default={pokemon.front_default}
            handleNext={handleNext}
            handlePrev={handlePrev}
            height={pokemon.height}
            id={pokemon.id}
            name={pokemon.name}
            stats={pokemon.stats}
            types={pokemon.types}
            weight={pokemon.weight}
          />
        </MainLayout>
      )}
    </div>
  );
};

export default PokemonInfo;
